version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: solarapp
      MYSQL_USER: root
      MYSQL_PASSWORD: password
